### ISSUE TITLE
Fix your dang lua parens getting highlighted as errors

### ISSUE THREAD

**Issue by euclidianAce** [tjdevries/config_manager#11]
I didn't wanna bother with a pr for this but it should be as simple as making a `nvim/plugin/syntax/lua.vim` with
```viml
syntax match luaFunctionCall display /\k*\ze[ \n\t\r]*\(["'({]\|\[=*\[\)/
```
(it should go in plugin so that it loads before the actual syntax file keeps the intended behavior of not highlighting function names in definitions)
and removing the other definition of `luaFunctionCall` in `nvim/after/syntax/lua.vim`

(Also I have a Lua syntax plugin that does this, and includes EmmyLua highlighting, [here](https://github.com/euclidianAce/BetterLua.vim))

**Comment by tjdevries** [comment]
Ok, fixed in the most recent push :)

Do you know how to do EmmyLua information for keys of a table? I want to tell EmmyLua what I expect as keys?

**Comment by tjdevries** [comment]
(I used your plugin btw, very cool)

**Comment by euclidianAce** [comment]
> Do you know how to do EmmyLua information for keys of a table? I want to tell EmmyLua what I expect as keys?

I believe the syntax is
```
---@type table<string, number>
```
For a map of strings to numbers. Its a little hard to find english resouces about emmylua but emmylua.github.io has a decent amount

**Comment by tjdevries** [comment]
I was wondering like:
```
---@type table opts Table with keys:
---@key foo string A foo
---@key bar number A Bar
```

etc.

**Comment by euclidianAce** [comment]
If I'm reading that correctly you want to annotate that a table has a key 'foo' that is a string? As in `type(t.foo) == "string"`?
You could use the `@class` and `@field` directives though. I think this would be what you want? I'll admit its been a hot minute since I've used emmylua's type stuffs.
```
---@class Thing
---@field foo string
---@field bar number

---@type Thing
local t = {}
```

**Comment by tjdevries** [comment]
Ah, that's a smart idea -- classes are just "fancy tables" after all. I will try that out at some point. Thanks :)
