### ISSUE TITLE
You told me to leave this 👍

### ISSUE THREAD

**Issue by brandoncc** [tjdevries/config_manager#12]
```
nnoremap <Leader>gw <cmd>call execute(':FzfPreviewProjectGrep ' . expand("<cword>"))<CR>
vnoremap <Leader>gw <cmd>call execute(':FzfPreviewProjectGrep ' . "'<,'>")<CR>
```

I'm trying to make the first mapping work in visual mode, but the second mapping doesn't work.

**Comment by brandoncc** [comment]
I tried the same thing in telescope, but didn't get anywhere either:

```
vnoremap <Leader>gw :lua require'telescope.builtin'.grep_string{search = expand("'<,'>")}
```

This results in:

```
E5108: Error executing lua [string ":lua"]:1: attempt to call global 'expand' (a nil value)
```

**Comment by tjdevries** [comment]
you would need `vim.fn.expand` since it's Lua inside of there.

**Comment by tjdevries** [comment]
but I still don't think that would work -- I don't think that's how you get the text within a visual selection.

**Comment by tjdevries** [comment]
You'd need something like this:

https://stackoverflow.com/questions/1533565/how-to-get-visually-selected-text-in-vimscript

You could re-write that in Lua probably or maybe even use something like `vim.region` to help you.

You probably want to write a Lua funciton to do this -- or make a PR for something like `telescope.util.get_visual_selection` or something

**Comment by brandoncc** [comment]
I have been on that SO post before 😂
Thanks!

**Comment by brandoncc** [comment]
I even have it in my config repo 😹 

https://github.com/brandoncc/nvim/blob/master/after/plugin/ultisnips.vim#L78-L102
