### ISSUE TITLE
Elixir learning links

### ISSUE THREAD

**Issue by jakeperry** [tjdevries/config_manager#13]
**Free**
[Elixir Website](https://elixir-lang.org/learning.html)
[Elixir School](https://elixirschool.com/en/) 
[Elixir Nerves Project](https://www.nerves-project.org/) Could be a fun project to start with and they are really helpful

**Paid**
[Grox IO](https://grox.io/) offers courses and training sessions
[Udemy](https://www.udemy.com) has some good courses

**Books**
The Little Book of Elixir and OTP
Elixir in Action
Real-time Phoenix

**Comment by tjdevries** [comment]
(I actually looked at some of these!! Thanks :) I might try something out on stream sometime, seems like an interesting language)

**Comment by jakeperry** [comment]
That would be cool!  Let me know which stream.
