### ISSUE TITLE
[Question] how does packer get loaded?

### ISSUE THREAD

**Issue by ncaycedo** [tjdevries/config_manager#23]
Hi! I'm trying to improve my nvim config by taking inspiration from more experienced users. I understand the bootstrapping and partially how the config for different plugins gets autoloaded, but I'm not sure where you're loading packer and calling `:PackerSync` or `packer.sync()`. My guess is you do it manually, but I tried it on my pc and packer doesn't seem to be loaded at all.

Can you tell me how have configured packer? =)

**Comment by tjdevries** [comment]
It only gets loaded when I source my `plugins.lua` file (not every time I open nvim)
