### ISSUE TITLE
How to install your dot files?

### ISSUE THREAD

**Issue by rjmccabe3701** [tjdevries/config_manager#24]
I have been pilfering some of your nvim config for a few months now but I figured I would play around with your config, as is, to get a better feel for what I like. The only problem is how are you installing your dot files?.  I see a mention of a ``link_dirs.sh`` in your [makefile](https://github.com/tjdevries/config_manager/blob/master/makefile#L17) but that script DNE in this repo.

**Comment by tjdevries** [comment]
Sorry, it's not for installing for other people. If you're looking for something quick to start w/ nvim, you should check out github.com/nvim-lua/kickstart.nvim
